### ISSUE TITLE
Official wallet 1.7.0 offers are not supported

### ISSUE THREAD

**Issue by bbjubjub2494** [greimela/nostr-dex#1]
Offers created with Chia 1.7.0 do not show up in the frontend. This seems to be caused by the new offer format based on the web console errors:
```
Error: The data is compressed with version 6 and cannot be parsed. Update software and try again.
    NuxtJS 8
entry.ab974e08.js:4159:89230
    NuxtJS 6
```

To reproduce, check `USDS` offers [in the Webapp.](https://nostr-dex.vercel.app/asset/6d95dae356e32a71db5ddcb42224754a02524c615c5fc35f568c2af04774e589)

**Comment by greimela** [comment]
Thank you for your report, the new offers are now supported!
